/**
 * Video Registry
 * Auto-generated by scripts/index-videos.ts on 2025-12-30
 */

export interface VideoAsset {
    id: string;
    url: string;
    originalSource: string;
    description: string;
    tags: string[];
    mood: string;
    colorPalette: string[];
}

export const VIDEO_REGISTRY: Record<string, VideoAsset> = {
    'andara_ionic_drop__water__ionic__dna-scene_1_0s': {
        id: 'andara_ionic_drop__water__ionic__dna-scene_1_0s',
        url: '/videos/processed/andara_ionic_drop__water__ionic__dna/scene_1_0s.mp4',
        originalSource: "Andara_Ionic_drop, water, ionic, dna.mp4",
        description: "Andara Ionic drop showing structured liquid crystal formation.",
        tags: ["water","ionic","dna","quantum","liquid crystal"],
        mood: "Ethereal",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'andara_ionic_drop__water__ionic__dna-scene_2_2s': {
        id: 'andara_ionic_drop__water__ionic__dna-scene_2_2s',
        url: '/videos/processed/andara_ionic_drop__water__ionic__dna/scene_2_2s.mp4',
        originalSource: "Andara_Ionic_drop, water, ionic, dna.mp4",
        description: "Andara Ionic drop showing structured liquid crystal formation.",
        tags: ["water","ionic","dna","quantum","liquid crystal"],
        mood: "Ethereal",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'andara_ionic_drop__water__ionic__dna-scene_3_4s': {
        id: 'andara_ionic_drop__water__ionic__dna-scene_3_4s',
        url: '/videos/processed/andara_ionic_drop__water__ionic__dna/scene_3_4s.mp4',
        originalSource: "Andara_Ionic_drop, water, ionic, dna.mp4",
        description: "Andara Ionic drop showing structured liquid crystal formation.",
        tags: ["water","ionic","dna","quantum","liquid crystal"],
        mood: "Ethereal",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'black_mica_genesis_volcanic_origin-scene_1_0s': {
        id: 'black_mica_genesis_volcanic_origin-scene_1_0s',
        url: '/videos/processed/black_mica_genesis_volcanic_origin/scene_1_0s.mp4',
        originalSource: "Black_Mica_Genesis_Volcanic_Origin.mp4",
        description: "Formation of Black Mica from deep earth volcanic sources.",
        tags: ["mica","volcanic","origin","mineral","genesis"],
        mood: "Primordial",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'directorial_vision_for_veo_video-scene_1_0s': {
        id: 'directorial_vision_for_veo_video-scene_1_0s',
        url: '/videos/processed/directorial_vision_for_veo_video/scene_1_0s.mp4',
        originalSource: "Directorial_Vision_For_Veo_Video.mp4",
        description: "Video content: Directorial Vision For Veo Video",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'directorial_vision_for_veo_video-scene_2_2s': {
        id: 'directorial_vision_for_veo_video-scene_2_2s',
        url: '/videos/processed/directorial_vision_for_veo_video/scene_2_2s.mp4',
        originalSource: "Directorial_Vision_For_Veo_Video.mp4",
        description: "Video content: Directorial Vision For Veo Video",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'directorial_vision_for_veo_video-scene_3_4s': {
        id: 'directorial_vision_for_veo_video-scene_3_4s',
        url: '/videos/processed/directorial_vision_for_veo_video/scene_3_4s.mp4',
        originalSource: "Directorial_Vision_For_Veo_Video.mp4",
        description: "Video content: Directorial Vision For Veo Video",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'product_video_animation_ionic_mineral_solution-scene_1_0s': {
        id: 'product_video_animation_ionic_mineral_solution-scene_1_0s',
        url: '/videos/processed/product_video_animation_ionic_mineral_solution/scene_1_0s.mp4',
        originalSource: "Product_Video_Animation_Ionic_Mineral_Solution.mp4",
        description: "Video content: Product Video Animation Ionic Mineral Solution",
        tags: ["ionic","ion","mineral"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'product_video_generation_request-scene_1_0s': {
        id: 'product_video_generation_request-scene_1_0s',
        url: '/videos/processed/product_video_generation_request/scene_1_0s.mp4',
        originalSource: "Product_Video_Generation_Request.mp4",
        description: "Video content: Product Video Generation Request",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'droy__water__electric__tructured_-scene_1_0s': {
        id: 'droy__water__electric__tructured_-scene_1_0s',
        url: '/videos/processed/droy__water__electric__tructured_/scene_1_0s.mp4',
        originalSource: "droy, water, electric, tructured .mp4",
        description: "Video content: droy, water, electric, tructured",
        tags: ["water","aqua","liquid","hydration","electric","voltage","energy","charge"],
        mood: "Energetic",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'product_video__2-scene_1_0s': {
        id: 'product_video__2-scene_1_0s',
        url: '/videos/processed/product_video__2/scene_1_0s.mp4',
        originalSource: "product video -2.mp4",
        description: "Video content: product video 2",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'product_video_v0_7-scene_1_0s': {
        id: 'product_video_v0_7-scene_1_0s',
        url: '/videos/processed/product_video_v0_7/scene_1_0s.mp4',
        originalSource: "product video v0.7.mp4",
        description: "Video content: product video v0.7",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'sample_0_3-scene_1_0s': {
        id: 'sample_0_3-scene_1_0s',
        url: '/videos/processed/sample_0_3/scene_1_0s.mp4',
        originalSource: "sample_0-3.mp4",
        description: "Video content: sample 0 3",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'sample_1_2-scene_1_0s': {
        id: 'sample_1_2-scene_1_0s',
        url: '/videos/processed/sample_1_2/scene_1_0s.mp4',
        originalSource: "sample_1-2.mp4",
        description: "Video content: sample 1 2",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'sample_1_3-scene_1_0s': {
        id: 'sample_1_3-scene_1_0s',
        url: '/videos/processed/sample_1_3/scene_1_0s.mp4',
        originalSource: "sample_1-3.mp4",
        description: "Video content: sample 1 3",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'sample_1_3-scene_2_2s': {
        id: 'sample_1_3-scene_2_2s',
        url: '/videos/processed/sample_1_3/scene_2_2s.mp4',
        originalSource: "sample_1-3.mp4",
        description: "Video content: sample 1 3",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'sample_1_3-scene_3_4s': {
        id: 'sample_1_3-scene_3_4s',
        url: '/videos/processed/sample_1_3/scene_3_4s.mp4',
        originalSource: "sample_1-3.mp4",
        description: "Video content: sample 1 3",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'sample_1_3-scene_4_6s': {
        id: 'sample_1_3-scene_4_6s',
        url: '/videos/processed/sample_1_3/scene_4_6s.mp4',
        originalSource: "sample_1-3.mp4",
        description: "Video content: sample 1 3",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'sample_1-scene_1_0s': {
        id: 'sample_1-scene_1_0s',
        url: '/videos/processed/sample_1/scene_1_0s.mp4',
        originalSource: "sample_1.mp4",
        description: "Video content: sample 1",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'sample_1-scene_2_2s': {
        id: 'sample_1-scene_2_2s',
        url: '/videos/processed/sample_1/scene_2_2s.mp4',
        originalSource: "sample_1.mp4",
        description: "Video content: sample 1",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'sample_3-scene_1_0s': {
        id: 'sample_3-scene_1_0s',
        url: '/videos/processed/sample_3/scene_1_0s.mp4',
        originalSource: "sample_3.mp4",
        description: "Video content: sample 3",
        tags: ["video","media","content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'water_frop_electric_structure-scene_1_0s': {
        id: 'water_frop_electric_structure-scene_1_0s',
        url: '/videos/processed/water_frop_electric_structure/scene_1_0s.mp4',
        originalSource: "water frop electric structure.mp4",
        description: "Visualization of electric charge structure in water.",
        tags: ["electric","water","structure","charge","voltage"],
        mood: "Energetic",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    },

    'water_frop_electric_structure-scene_2_2s': {
        id: 'water_frop_electric_structure-scene_2_2s',
        url: '/videos/processed/water_frop_electric_structure/scene_2_2s.mp4',
        originalSource: "water frop electric structure.mp4",
        description: "Visualization of electric charge structure in water.",
        tags: ["electric","water","structure","charge","voltage"],
        mood: "Energetic",
        colorPalette: ["#1a1a2e","#16213e","#0f3460"]
    }
};

export function getVideoAsset(id: string): VideoAsset | undefined {
    return VIDEO_REGISTRY[id];
}

export function getAllVideos(): VideoAsset[] {
    return Object.values(VIDEO_REGISTRY);
}
