/**
 * Video Registry
 * Auto-generated by scripts/index-videos.ts on 2026-01-09
 */

export interface VideoAsset {
    id: string;
    url: string;
    originalSource: string;
    description: string;
    tags: string[];
    mood: string;
    colorPalette: string[];
}

export const VIDEO_REGISTRY: Record<string, VideoAsset> = {
    'andara_ionic_drop__water__ionic__dna-scene_1_0s': {
        id: 'andara_ionic_drop__water__ionic__dna-scene_1_0s',
        url: '/videos/processed/andara_ionic_drop__water__ionic__dna/scene_1_0s.mp4',
        originalSource: "Andara_Ionic_drop, water, ionic, dna.mp4",
        description: "Andara Ionic drop showing structured liquid crystal formation.",
        tags: ["water", "ionic", "dna", "quantum", "liquid crystal"],
        mood: "Ethereal",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    'andara_ionic_drop__water__ionic__dna-scene_2_2s': {
        id: 'andara_ionic_drop__water__ionic__dna-scene_2_2s',
        url: '/videos/processed/andara_ionic_drop__water__ionic__dna/scene_2_2s.mp4',
        originalSource: "Andara_Ionic_drop, water, ionic, dna.mp4",
        description: "Andara Ionic drop showing structured liquid crystal formation.",
        tags: ["water", "ionic", "dna", "quantum", "liquid crystal"],
        mood: "Ethereal",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    'andara_ionic_drop__water__ionic__dna-scene_3_4s': {
        id: 'andara_ionic_drop__water__ionic__dna-scene_3_4s',
        url: '/videos/processed/andara_ionic_drop__water__ionic__dna/scene_3_4s.mp4',
        originalSource: "Andara_Ionic_drop, water, ionic, dna.mp4",
        description: "Andara Ionic drop showing structured liquid crystal formation.",
        tags: ["water", "ionic", "dna", "quantum", "liquid crystal"],
        mood: "Ethereal",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    'black_mica_genesis_volcanic_origin-scene_1_0s': {
        id: 'black_mica_genesis_volcanic_origin-scene_1_0s',
        url: '/videos/processed/black_mica_genesis_volcanic_origin/scene_1_0s.mp4',
        originalSource: "Black_Mica_Genesis_Volcanic_Origin.mp4",
        description: "Formation of Black Mica from deep earth volcanic sources.",
        tags: ["mica", "volcanic", "origin", "mineral", "genesis"],
        mood: "Primordial",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    'please_let_fall_202601092131_lv39r-scene_1_0s': {
        id: 'please_let_fall_202601092131_lv39r-scene_1_0s',
        url: '/videos/processed/please_let_fall_202601092131_lv39r/scene_1_0s.mp4',
        originalSource: "Please_let_fall_202601092131_lv39r.mp4",
        description: "Nature's Coherence: Noise to ordered wave pattern transition.",
        tags: ["coherence", "nature", "order", "pattern"],
        mood: "Calming",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__cinematic_202601092134_rnk3w-scene_1_0s': {
        id: '__cinematic_202601092134_rnk3w-scene_1_0s',
        url: '/videos/processed/__cinematic_202601092134_rnk3w/scene_1_0s.mp4',
        originalSource: "__cinematic_202601092134_rnk3w.mp4",
        description: "Final Unity: Elements merging into a single sphere of light.",
        tags: ["unity", "one", "whole", "light"],
        mood: "Harmonious",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__cinematic_202601092134_rnk3w-scene_2_1s': {
        id: '__cinematic_202601092134_rnk3w-scene_2_1s',
        url: '/videos/processed/__cinematic_202601092134_rnk3w/scene_2_1s.mp4',
        originalSource: "__cinematic_202601092134_rnk3w.mp4",
        description: "Final Unity: Elements merging into a single sphere of light.",
        tags: ["unity", "one", "whole", "light"],
        mood: "Harmonious",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092128_di6q9-scene_1_0s': {
        id: '__video_202601092128_di6q9-scene_1_0s',
        url: '/videos/processed/__video_202601092128_di6q9/scene_1_0s.mp4',
        originalSource: "__video_202601092128_di6q9.mp4",
        description: "Electric Awakening: Still water coming alive with voltage arcs.",
        tags: ["electric", "activation", "charge", "bioelectric"],
        mood: "Energetic",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092129_9i3ze-scene_1_0s': {
        id: '__video_202601092129_9i3ze-scene_1_0s',
        url: '/videos/processed/__video_202601092129_9i3ze/scene_1_0s.mp4',
        originalSource: "__video_202601092129_9i3ze.mp4",
        description: "Mineral Lattice: 3D visualization of tetrahedral ionic mineral structure.",
        tags: ["mineral", "lattice", "geometry", "crystalline"],
        mood: "Scientific",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092129_ce3mw-scene_1_0s': {
        id: '__video_202601092129_ce3mw-scene_1_0s',
        url: '/videos/processed/__video_202601092129_ce3mw/scene_1_0s.mp4',
        originalSource: "__video_202601092129_ce3mw.mp4",
        description: "Field Lines: Human bioelectric field lines tracing meridian pathways.",
        tags: ["electric", "voltage", "field", "terrain"],
        mood: "Living",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092129_lg9aa-scene_1_0s': {
        id: '__video_202601092129_lg9aa-scene_1_0s',
        url: '/videos/processed/__video_202601092129_lg9aa/scene_1_0s.mp4',
        originalSource: "__video_202601092129_lg9aa.mp4",
        description: "Vortex Spiral: Perfect water vortex spinning with golden-ratio curve.",
        tags: ["water", "vortex", "spiral", "structure"],
        mood: "Fluid",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092129_ydptq-scene_1_0s': {
        id: '__video_202601092129_ydptq-scene_1_0s',
        url: '/videos/processed/__video_202601092129_ydptq/scene_1_0s.mp4',
        originalSource: "__video_202601092129_ydptq.mp4",
        description: "DNA Resonance: Translucent crystalline DNA double helix rotation.",
        tags: ["resonance", "dna", "cell", "frequency"],
        mood: "Scientific",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092130_0yffh-scene_1_0s': {
        id: '__video_202601092130_0yffh-scene_1_0s',
        url: '/videos/processed/__video_202601092130_0yffh/scene_1_0s.mp4',
        originalSource: "__video_202601092130_0yffh.mp4",
        description: "Earth to Crystal: Raw volcanic earth transforming into glowing crystal.",
        tags: ["vision", "earth", "ethereal", "transformation"],
        mood: "Transformative",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092130_1bpzh-scene_1_0s': {
        id: '__video_202601092130_1bpzh-scene_1_0s',
        url: '/videos/processed/__video_202601092130_1bpzh/scene_1_0s.mp4',
        originalSource: "__video_202601092130_1bpzh.mp4",
        description: "Liquid Gold: Amber-gold ionic mineral solution in premium bottle.",
        tags: ["product", "ionic", "gold", "activation"],
        mood: "Alchemical",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092130_i44o5-scene_1_0s': {
        id: '__video_202601092130_i44o5-scene_1_0s',
        url: '/videos/processed/__video_202601092130_i44o5/scene_1_0s.mp4',
        originalSource: "__video_202601092130_i44o5.mp4",
        description: "Clarification Phase: Mineral drop entering water and settling particles.",
        tags: ["drop", "clarify", "settle", "flocculation"],
        mood: "Scientific",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092130_yxp2e-scene_1_0s': {
        id: '__video_202601092130_yxp2e-scene_1_0s',
        url: '/videos/processed/__video_202601092130_yxp2e/scene_1_0s.mp4',
        originalSource: "__video_202601092130_yxp2e.mp4",
        description: "Neural Network: Mineral particles forming intelligent mesh connections.",
        tags: ["intelligence", "mineral", "network", "particle"],
        mood: "Cosmic",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092130_zyoyz-scene_1_0s': {
        id: '__video_202601092130_zyoyz-scene_1_0s',
        url: '/videos/processed/__video_202601092130_zyoyz/scene_1_0s.mp4',
        originalSource: "__video_202601092130_zyoyz.mp4",
        description: "Atomic Orbitals: Mineral atom with pulsing electron shells.",
        tags: ["atom", "ion", "electron", "charge"],
        mood: "Scientific",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092131_i3iey-scene_1_0s': {
        id: '__video_202601092131_i3iey-scene_1_0s',
        url: '/videos/processed/__video_202601092131_i3iey/scene_1_0s.mp4',
        originalSource: "__video_202601092131_i3iey.mp4",
        description: "Crystalline River: River bed of crystals with flowing clear water.",
        tags: ["river", "crystal", "water", "flow"],
        mood: "Ethereal",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092131_ubde1-scene_1_0s': {
        id: '__video_202601092131_ubde1-scene_1_0s',
        url: '/videos/processed/__video_202601092131_ubde1/scene_1_0s.mp4',
        originalSource: "__video_202601092131_ubde1.mp4",
        description: "Ionic Flow: Stream of charged water molecules moving like stars.",
        tags: ["flow", "current", "charge", "stream"],
        mood: "Fluid",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092131_vubq0-scene_1_0s': {
        id: '__video_202601092131_vubq0-scene_1_0s',
        url: '/videos/processed/__video_202601092131_vubq0/scene_1_0s.mp4',
        originalSource: "__video_202601092131_vubq0.mp4",
        description: "Fern Fractal: Bioluminescent fern unfurling in Fibonacci spiral.",
        tags: ["fractal", "nature", "growth", "green"],
        mood: "Organic",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092132_9fytd-scene_1_0s': {
        id: '__video_202601092132_9fytd-scene_1_0s',
        url: '/videos/processed/__video_202601092132_9fytd/scene_1_0s.mp4',
        originalSource: "__video_202601092132_9fytd.mp4",
        description: "The Observer: Polished obsidian sphere reflecting the galaxy.",
        tags: ["observer", "eye", "perception", "awareness"],
        mood: "Mystical",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092132_gs92a-scene_1_0s': {
        id: '__video_202601092132_gs92a-scene_1_0s',
        url: '/videos/processed/__video_202601092132_gs92a/scene_1_0s.mp4',
        originalSource: "__video_202601092132_gs92a.mp4",
        description: "Voltage Gate: Molecular view of ion channels opening.",
        tags: ["voltage", "gate", "cell", "membrane"],
        mood: "Scientific",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092132_ldlrm-scene_1_0s': {
        id: '__video_202601092132_ldlrm-scene_1_0s',
        url: '/videos/processed/__video_202601092132_ldlrm/scene_1_0s.mp4',
        originalSource: "__video_202601092132_ldlrm.mp4",
        description: "Mineral Consciousness: Floating geode with brain-like light rhythm.",
        tags: ["consciousness", "mind", "spirit", "glow"],
        mood: "Spiritual",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092132_u592f-scene_1_0s': {
        id: '__video_202601092132_u592f-scene_1_0s',
        url: '/videos/processed/__video_202601092132_u592f/scene_1_0s.mp4',
        originalSource: "__video_202601092132_u592f.mp4",
        description: "Electric Earth: Roots in soil glowing with white bio-electricity.",
        tags: ["earth", "grounding", "electric", "soil"],
        mood: "Biological",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092133_9bmeg-scene_1_0s': {
        id: '__video_202601092133_9bmeg-scene_1_0s',
        url: '/videos/processed/__video_202601092133_9bmeg/scene_1_0s.mp4',
        originalSource: "__video_202601092133_9bmeg.mp4",
        description: "Liquid Crystal Brain: Flowing liquid crystal in brain shape.",
        tags: ["brain", "liquid", "thought", "connect"],
        mood: "Abstract",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092133_mkw85-scene_1_0s': {
        id: '__video_202601092133_mkw85-scene_1_0s',
        url: '/videos/processed/__video_202601092133_mkw85/scene_1_0s.mp4',
        originalSource: "__video_202601092133_mkw85.mp4",
        description: "Thunderstone: Conductive mineral struck by micro-lightning.",
        tags: ["thunder", "power", "energy", "stone"],
        mood: "Energetic",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092134_319bc-scene_1_0s': {
        id: '__video_202601092134_319bc-scene_1_0s',
        url: '/videos/processed/__video_202601092134_319bc/scene_1_0s.mp4',
        originalSource: "__video_202601092134_319bc.mp4",
        description: "Video content: video 202601092134 319bc",
        tags: ["video", "media", "content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '__video_202601092134_nfnqj-scene_1_0s': {
        id: '__video_202601092134_nfnqj-scene_1_0s',
        url: '/videos/processed/__video_202601092134_nfnqj/scene_1_0s.mp4',
        originalSource: "__video_202601092134_nfnqj.mp4",
        description: "Video content: video 202601092134 nfnqj",
        tags: ["video", "media", "content"],
        mood: "Neutral",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '_video_1_1080p_202601092128-scene_1_0s': {
        id: '_video_1_1080p_202601092128-scene_1_0s',
        url: '/videos/processed/_video_1_1080p_202601092128/scene_1_0s.mp4',
        originalSource: "_video_1_1080p_202601092128.mp4",
        description: "Primordial Drop: Golden mineral water drop fall in slow motion.",
        tags: ["home", "hero", "primordial", "drop"],
        mood: "Ethereal",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '_video_2_202601092128_ot0s9-scene_1_0s': {
        id: '_video_2_202601092128_ot0s9-scene_1_0s',
        url: '/videos/processed/_video_2_202601092128_ot0s9/scene_1_0s.mp4',
        originalSource: "_video_2_202601092128_ot0s9.mp4",
        description: "Volcanic Genesis: Molten rock transforming into crystalline mica.",
        tags: ["volcanic", "origin", "mica", "genesis"],
        mood: "Primordial",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    '_video_3_202601092128_xemjk-scene_1_0s': {
        id: '_video_3_202601092128_xemjk-scene_1_0s',
        url: '/videos/processed/_video_3_202601092128_xemjk/scene_1_0s.mp4',
        originalSource: "_video_3_202601092128_xemjk.mp4",
        description: "Ionic Hexagon: Hexagonal water molecules interlocking in geometric patterns.",
        tags: ["ionic", "clarity", "hexagonal", "structure"],
        mood: "Scientific",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    'droy__water__electric__tructured_-scene_1_0s': {
        id: 'droy__water__electric__tructured_-scene_1_0s',
        url: '/videos/processed/droy__water__electric__tructured_/scene_1_0s.mp4',
        originalSource: "droy, water, electric, tructured .mp4",
        description: "Video content: droy, water, electric, tructured",
        tags: ["water", "aqua", "liquid", "hydration", "electric", "voltage", "energy", "charge"],
        mood: "Energetic",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    'water_frop_electric_structure-scene_1_0s': {
        id: 'water_frop_electric_structure-scene_1_0s',
        url: '/videos/processed/water_frop_electric_structure/scene_1_0s.mp4',
        originalSource: "water frop electric structure.mp4",
        description: "Visualization of electric charge structure in water.",
        tags: ["electric", "water", "structure", "charge", "voltage"],
        mood: "Energetic",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    'water_frop_electric_structure-scene_2_2s': {
        id: 'water_frop_electric_structure-scene_2_2s',
        url: '/videos/processed/water_frop_electric_structure/scene_2_2s.mp4',
        originalSource: "water frop electric structure.mp4",
        description: "Visualization of electric charge structure in water.",
        tags: ["electric", "water", "structure", "charge", "voltage"],
        mood: "Energetic",
        colorPalette: ["#1a1a2e", "#16213e", "#0f3460"]
    },

    /* --- NEW PREMIUM BACKGROUND VIDEOS (JAN 2026) --- */

    'terrain-overview-bg': {
        id: 'terrain-overview-bg',
        url: '/videos/backgrounds/terrain-overview-bg.mp4',
        originalSource: "_scene_internal_202601101144_lizgu.mp4",
        description: "Internal ecosystem visualization of the terrain model.",
        tags: ["terrain", "ecosystem", "landscape", "field", "green"],
        mood: "Expansive",
        colorPalette: ["#0a2e1a", "#1a4d2e", "#2cff9a"]
    },
    'terrain-sulfur-bg': {
        id: 'terrain-sulfur-bg',
        url: '/videos/backgrounds/terrain-sulfur-bg.mp4',
        originalSource: "_scene_sulfur_202601101144_w6o0d.mp4",
        description: "Golden sulfur integration in terrain landscape.",
        tags: ["sulfur", "terrain", "yellow", "mineral", "detox"],
        mood: "Transformative",
        colorPalette: ["#ffd700", "#ff8c00", "#b22222"]
    },
    'cell-voltage-bg': {
        id: 'cell-voltage-bg',
        url: '/videos/backgrounds/cell-voltage-bg.mp4',
        originalSource: "_scene_6_202601101145_ycjc0.mp4",
        description: "Cell membrane electrical activity and voltage gradients.",
        tags: ["cell", "voltage", "membrane", "electric", "battery"],
        mood: "Scientific",
        colorPalette: ["#000080", "#00ffff", "#ffa500"]
    },
    'conductivity-signals-bg': {
        id: 'conductivity-signals-bg',
        url: '/videos/backgrounds/conductivity-signals-bg.mp4',
        originalSource: "_scene_conductivity_202601101145_ng98l.mp4",
        description: "Signal pathway and nerve-like electrical transmission.",
        tags: ["conductivity", "signals", "nerve", "current", "transmission"],
        mood: "Fast",
        colorPalette: ["#000000", "#00ffff", "#0000ff"]
    },
    'geometry-consciousness-bg': {
        id: 'geometry-consciousness-bg',
        url: '/videos/backgrounds/geometry-consciousness-bg.mp4',
        originalSource: "_scene_geometryconsciousness_202601101145.mp4",
        description: "Sacred geometry unfolding and pattern recognition.",
        tags: ["geometry", "sacred", "consciousness", "mandala", "purple"],
        mood: "Mysterious",
        colorPalette: ["#4b0082", "#9370db", "#ffd700"]
    },
    'crystalline-matrix-bg': {
        id: 'crystalline-matrix-bg',
        url: '/videos/backgrounds/crystalline-matrix-bg.mp4',
        originalSource: "_scene_render_202601101146_vr3vz.mp4",
        description: "Crystalline matrix and molecular lattice formation.",
        tags: ["crystalline", "matrix", "geometry", "structure", "light"],
        mood: "Precise",
        colorPalette: ["#f0ffff", "#ff00ff", "#9370db"]
    },
    'crystal-memory-bg': {
        id: 'crystal-memory-bg',
        url: '/videos/backgrounds/crystal-memory-bg.mp4',
        originalSource: "_scene_crystal_202601101145_kol33.mp4",
        description: "Information storage visualization within a crystal matrix.",
        tags: ["crystal", "memory", "mineral", "lattice", "storage"],
        mood: "Deep",
        colorPalette: ["#ffffff", "#800080", "#ffd700"]
    },
    'water-structure-bg': {
        id: 'water-structure-bg',
        url: '/videos/backgrounds/water-structure-bg.mp4',
        originalSource: "_scene_14_202601101146_qp9ch.mp4",
        description: "Water molecular organization and hydrogen bonding clusters.",
        tags: ["water", "structure", "molecular", "cluster", "blue"],
        mood: "Fluid",
        colorPalette: ["#00008b", "#00ffff", "#ffffff"]
    },
    'water-phases-bg': {
        id: 'water-phases-bg',
        url: '/videos/backgrounds/water-phases-bg.mp4',
        originalSource: "_scene_15_202601101146_7h8cl.mp4",
        description: "Transition between bulk water and ordered EZ layer.",
        tags: ["water", "phases", "structure", "EZ", "hexagonal"],
        mood: "Revelatory",
        colorPalette: ["#0000ff", "#da70d6", "#ffd700"]
    },
    'mineral-cofactors-bg': {
        id: 'mineral-cofactors-bg',
        url: '/videos/backgrounds/mineral-cofactors-bg.mp4',
        originalSource: "_17_mineral_202601101146_rck7m.mp4",
        description: "Mineral ions activating enzyme sites through precise geometry.",
        tags: ["mineral", "enzyme", "cofactor", "catalysis", "gold"],
        mood: "Precise",
        colorPalette: ["#0000ff", "#ffd700", "#ffffff"]
    },
    'sulfate-structuring-bg': {
        id: 'sulfate-structuring-bg',
        url: '/videos/backgrounds/sulfate-structuring-bg.mp4',
        originalSource: "22_sulfatestructuringeztsx_path_20260110.mp4",
        description: "Sulfate ions creating ordered EZ water layers.",
        tags: ["sulfate", "EZ", "structuring", "water", "interface", "hexagonal", "blue", "geometry"],
        mood: "Organized",
        colorPalette: ["#ffd700", "#da70d6", "#0000ff"]
    },
    'liquid-crystal-biology-bg': {
        id: 'liquid-crystal-biology-bg',
        url: '/videos/backgrounds/liquid-crystal-biology-bg.mp4',
        originalSource: "_scene_biological_202601101146_hy20l.mp4",
        description: "Biological liquid crystals and collagen matrix alignment.",
        tags: ["liquid", "crystal", "biology", "collagen", "order"],
        mood: "Harmonious",
        colorPalette: ["#ffe4e1", "#e6e6fa", "#800080"]
    },
    'proton-gradients-bg': {
        id: 'proton-gradients-bg',
        url: '/videos/backgrounds/proton-gradients-bg.mp4',
        originalSource: "_25_proton_202601101146_0yz0h.mp4",
        description: "Proton pumping and ATP energy generation in mitochondria.",
        tags: ["proton", "gradient", "ATP", "energy", "mitochondria"],
        mood: "Energetic",
        colorPalette: ["#008000", "#ff8c00", "#ffff00"]
    },
    'light-mineral-field-bg': {
        id: 'light-mineral-field-bg',
        url: '/videos/backgrounds/light-mineral-field-bg.mp4',
        originalSource: "_scene_26_202601101147_i9dh7.mp4",
        description: "Light interacting with and revealing a mineral field.",
        tags: ["light", "mineral", "field", "photon", "golden"],
        mood: "Illuminated",
        colorPalette: ["#ffffff", "#ffd700", "#ff00ff"]
    },
    'sulfur-springs-tradition-bg': {
        id: 'sulfur-springs-tradition-bg',
        url: '/videos/backgrounds/sulfur-springs-tradition-bg.mp4',
        originalSource: "_scene_treatment_202601101144_e0p7r.mp4",
        description: "Steaming traditional sulfur spring in ancient landscape.",
        tags: ["sulfur", "springs", "healing", "tradition", "thermal", "volcanic", "yellow", "ancient"],
        mood: "Ancient",
        colorPalette: ["#8b4513", "#ffff00", "#ffffff"]
    },
    'sourcing-sustainability-bg': {
        id: 'sourcing-sustainability-bg',
        url: '/videos/backgrounds/sourcing-sustainability-bg.mp4',
        originalSource: "_scene_30_202601101147_jmyed.mp4",
        description: "Pristine earth origin and sustainable volcanic mineral sourcing.",
        tags: ["source", "sustainability", "volcanic", "earth", "origin"],
        mood: "Pristine",
        colorPalette: ["#000000", "#ffd700", "#0000ff"]
    },
    'bioelectric-membrane-bg': {
        id: 'bioelectric-membrane-bg',
        url: '/videos/backgrounds/bioelectric-membrane-bg.mp4',
        originalSource: "ionic_minerals_bioelectric_membrane.mp4",
        description: "Cell membrane electrical activity and voltage pulses.",
        tags: ["bioelectric", "membrane", "cell", "voltage", "potential"],
        mood: "Active",
        colorPalette: ["#34d399", "#22d3ee", "#0a0c14"]
    },
    'cation-exchange-bg': {
        id: 'cation-exchange-bg',
        url: '/videos/backgrounds/cation-exchange-bg.mp4',
        originalSource: "ionic_minerals_cation_exchange.mp4",
        description: "Ionic exchange interaction between minerals and surfaces.",
        tags: ["cation", "exchange", "mineral", "interaction", "surface"],
        mood: "Precise",
        colorPalette: ["#f5a623", "#0a0c14", "#ffffff"]
    },
    'ion-conductivity-bg': {
        id: 'ion-conductivity-bg',
        url: '/videos/backgrounds/ion-conductivity-bg.mp4',
        originalSource: "ionic_minerals_conductivity.mp4",
        description: "Fluid conductivity and ionic signal pathways.",
        tags: ["conductivity", "ion", "signal", "flow", "current"],
        mood: "Fluid",
        colorPalette: ["#22d3ee", "#0a0c14", "#34d399"]
    },
    'ion-hero-bg': {
        id: 'ion-hero-bg',
        url: '/videos/backgrounds/ion-hero-bg.mp4',
        originalSource: "ionic_minerals_hero_charge.mp4",
        description: "Main hero visual for the ION cluster: charge and vitality.",
        tags: ["ion", "hero", "charge", "vitality", "potency"],
        mood: "Powerful",
        colorPalette: ["#f5a623", "#0a0c14", "#34d399"]
    },
    'hydration-shell-bg': {
        id: 'hydration-shell-bg',
        url: '/videos/backgrounds/hydration-shell-bg.mp4',
        originalSource: "ionic_minerals_hydration.mp4",
        description: "Molecular hydration shells forming around ionic centres.",
        tags: ["hydration", "shell", "molecule", "water", "structure"],
        mood: "Organized",
        colorPalette: ["#22d3ee", "#ffffff", "#0a0c14"]
    },
    'particle-network-bg': {
        id: 'particle-network-bg',
        url: '/videos/backgrounds/particle-network-bg.mp4',
        originalSource: "ionic_minerals_network.mp4",
        description: "Intelligent mineral particle network and mesh connectivity.",
        tags: ["network", "particle", "intelligence", "connectivity", "mesh"],
        mood: "Intelligent",
        colorPalette: ["#22d3ee", "#34d399", "#0a0c14"]
    },
    'ion-redox-bg': {
        id: 'ion-redox-bg',
        url: '/videos/backgrounds/ion-redox-bg.mp4',
        originalSource: "ionic_minerals_orp_redox.mp4",
        description: "Redox transformation and antioxidant potential.",
        tags: ["orp", "redox", "antioxidant", "potential", "charge"],
        mood: "Transformative",
        colorPalette: ["#34d399", "#f5a623", "#0a0c14"]
    },
    'volcanic-genesis-bg': {
        id: 'volcanic-genesis-bg',
        url: '/videos/backgrounds/volcanic-genesis-bg.mp4',
        originalSource: "ionic_minerals_volcanic_genesis.mp4",
        description: "Volcanic origin and primordial mineral creation.",
        tags: ["volcanic", "genesis", "origin", "magma", "primordial"],
        mood: "Ancient",
        colorPalette: ["#f5a623", "#0a0c14", "#34d399"]
    },
    'terrain-principles-bg': {
        id: 'terrain-principles-bg',
        url: '/videos/backgrounds/terrain-principles-bg.mp4',
        originalSource: "Please_let_fall_202601092131_lv39r.mp4",
        description: "Daily morning ritual and water rhythm.",
        tags: ["terrain", "daily", "ritual", "rhythm", "morning"],
        mood: "Calm",
        colorPalette: ["#34d399", "#ffffff", "#0a0c14"]
    },
    'dna-resonance-bg': {
        id: 'dna-resonance-bg',
        url: '/videos/backgrounds/dna-resonance-bg.mp4',
        originalSource: "Andara_Ionic_drop, water, ionic, dna.mp4",
        description: "DNA helix resonance and light frequency.",
        tags: ["dna", "resonance", "frequency", "cell", "light"],
        mood: "Mystical",
        colorPalette: ["#8b5cf6", "#22d3ee", "#0a0c14"]
    },
    'magma-genesis-bg': {
        id: 'magma-genesis-bg',
        url: '/videos/backgrounds/magma-genesis-bg.mp4',
        originalSource: "Black_Mica_Genesis_Volcanic_Origin.mp4",
        description: "Deep magma cooling into crystalline mica.",
        tags: ["magma", "volcanic", "mica", "genesis", "origin"],
        mood: "Profound",
        colorPalette: ["#0a0c14", "#f5a623", "#34d399"]
    },
    'electric-structure-bg': {
        id: 'electric-structure-bg',
        url: '/videos/backgrounds/electric-structure-bg.mp4',
        originalSource: "water frop electric structure.mp4",
        description: "Electric structure and charge distribution in water.",
        tags: ["electric", "charge", "structure", "water", "voltage"],
        mood: "Energetic",
        colorPalette: ["#22d3ee", "#0a0c14", "#f5a623"]
    },
    'flocculation-bg': {
        id: 'flocculation-bg',
        url: '/videos/backgrounds/flocculation-bg.mp4',
        originalSource: "droy, water, electric, tructured .mp4",
        description: "Flocculation process and particles settling for clarity.",
        tags: ["flocculation", "clarity", "purification", "settling", "process"],
        mood: "Clean",
        colorPalette: ["#ffffff", "#22d3ee", "#0a0c14"]
    },
    'charge-coherence-bg-alt': {
        id: 'charge-coherence-bg-alt',
        url: '/videos/backgrounds/charge-coherence-bg.mp4',
        originalSource: "_premium_cinematic_202601101145_mtplv.mp4",
        description: "Harmonious charge coherence and wave alignment.",
        tags: ["coherence", "charge", "wave", "alignment", "harmony"],
        mood: "Harmonious",
        colorPalette: ["#34d399", "#22d3ee", "#0a0c14"]
    },
    'microbiome-minerals-bg': {
        id: 'microbiome-minerals-bg',
        url: '/videos/backgrounds/microbiome-minerals-bg.mp4',
        originalSource: "_scene_the_202601101146_lpvxa.mp4",
        description: "Microbiome interaction with mineral pathways.",
        tags: ["microbiome", "bacteria", "minerals", "pathway", "biology"],
        mood: "Integrated",
        colorPalette: ["#8b5cf6", "#34d399", "#0a0c14"]
    },
    'sacred-geometry-bg': {
        id: 'sacred-geometry-bg',
        url: '/videos/backgrounds/sacred-geometry-bg.mp4',
        originalSource: "_scene_the_202601101146_5v8gd.mp4",
        description: "Sacred geometry mandalas and pattern recognition.",
        tags: ["geometry", "sacred", "mandala", "consciousness", "pattern"],
        mood: "Sacred",
        colorPalette: ["#8b5cf6", "#f5a623", "#0a0c14"]
    },
    'sulfate-anchor-bg': {
        id: 'sulfate-anchor-bg',
        url: '/videos/backgrounds/sulfate-anchor-bg.mp4',
        originalSource: "_scene_the_202601101147_l8vwj.mp4",
        description: "Sulfate tetrahedral geometry anchoring water clusters.",
        tags: ["sulfate", "anchor", "tetrahedral", "geometry", "water"],
        mood: "Stable",
        colorPalette: ["#22d3ee", "#f5a623", "#0a0c14"]
    },
    'rare-earth-glow-bg': {
        id: 'rare-earth-glow-bg',
        url: '/videos/backgrounds/rare-earth-glow-bg.mp4',
        originalSource: "_premium_cinematic_202601101146_p1dst.mp4",
        description: "Rare earth elements revealing their luminescent glow.",
        tags: ["rare-earth", "luminescence", "glow", "trace-mineral", "light"],
        mood: "Illuminated",
        colorPalette: ["#8b5cf6", "#34d399", "#0a0c14"]
    },
    'internal-ecosystem-bg': {
        id: 'internal-ecosystem-bg',
        url: '/videos/backgrounds/internal-ecosystem-bg.mp4',
        originalSource: '_scene_internal_202601101144_lizgu.mp4',
        description: "Internal ecosystem visualization for terrain science.",
        tags: ['terrain', 'internal', 'ecosystem', 'growth', 'green', 'complex'],
        mood: 'organic',
        colorPalette: ['green', 'emerald']
    },
    'water-treatment-bg': {
        id: 'water-treatment-bg',
        url: '/videos/backgrounds/water-treatment-bg.mp4',
        originalSource: '_scene_treatment_202601101144_e0p7r.mp4',
        description: "Water treatment and filtration process visualization.",
        tags: ['filtration', 'treatment', 'flow', 'industrial', 'blue'],
        mood: 'precise',
        colorPalette: ['blue', 'cyan']
    },
    'biological-matrix-bg': {
        id: 'biological-matrix-bg',
        url: '/videos/backgrounds/biological-matrix-bg.mp4',
        originalSource: '_scene_biological_202601101146_hy20l.mp4',
        description: "Complex biological matrix and cellular environments.",
        tags: ['biology', 'matrix', 'cell', 'complex', 'microscopic', 'purple'],
        mood: 'mystical',
        colorPalette: ['purple', 'indigo']
    },
    'ai-intelligence-concept': {
        id: 'ai-intelligence-concept',
        url: '/videos/backgrounds/ai-intelligence-concept.mp4',
        originalSource: '_ai_video_202601101145_hu49z.mp4',
        description: "AI intelligence and neural network concepts.",
        tags: ['ai', 'intelligence', 'neural', 'network', 'digital', 'abstract'],
        mood: 'Futuristic',
        colorPalette: ['#3b82f6', '#06b6d4', '#0a0c14']
    },
    'science-visualization-v1': {
        id: 'science-visualization-v1',
        url: '/videos/backgrounds/science-visualization-v1.mp4',
        originalSource: '_cinematic_visualization_202601101144_nj1z.mp4',
        description: "General science visualization for core pillars.",
        tags: ['science', 'visualization', 'cinematic', 'abstract', 'blue'],
        mood: 'Scientific',
        colorPalette: ['#1e3a8a', '#3b82f6', '#0a0c14']
    },
    'science-visualization-v2': {
        id: 'science-visualization-v2',
        url: '/videos/backgrounds/science-visualization-v2.mp4',
        originalSource: '_cinematic_visualization_202601101146_d6g4.mp4',
        description: "Microscopic molecular behavior visualization.",
        tags: ['microscopic', 'molecular', 'science', 'blue', 'dynamic'],
        mood: 'Deep',
        colorPalette: ['#172554', '#1e40af', '#0a0c14']
    },
    'science-visualization-v3': {
        id: 'science-visualization-v3',
        url: '/videos/backgrounds/science-visualization-v3.mp4',
        originalSource: '_cinematic_visualization_202601101147_u466.mp4',
        description: "Advanced scientific rendering of mineral signals.",
        tags: ['mineral', 'signal', 'transmission', 'science', 'structure'],
        mood: 'Analytical',
        colorPalette: ['#1e40af', '#60a5fa', '#0a0c14']
    },
    'andara-flow-abstract': {
        id: 'andara-flow-abstract',
        url: '/videos/backgrounds/andara-flow-abstract.mp4',
        originalSource: '_flow_prompts_202601101146_qmqy9.mp4',
        description: "Abstract representation of the Andara Flow UX.",
        tags: ['flow', 'ux', 'abstract', 'movement', 'interface'],
        mood: 'Fluid',
        colorPalette: ['#042f2e', '#14b8a6', '#0a0c14']
    },
    'primordial-origins-bg': {
        id: 'primordial-origins-bg',
        url: '/videos/backgrounds/primordial-origins-bg.mp4',
        originalSource: '_origins__202601101147_18y43.mp4',
        description: "The primordial origins of minerals and life.",
        tags: ['origins', 'primordial', 'mineral', 'genesis', 'nature'],
        mood: 'Primordial',
        colorPalette: ['#422006', '#92400e', '#0a0c14']
    },
    'premium-liquid-gold': {
        id: 'premium-liquid-gold',
        url: '/videos/backgrounds/premium-liquid-gold.mp4',
        originalSource: '_premium_cinematic_202601101145_5od3b.mp4',
        description: "Sleek liquid gold mineral behavior.",
        tags: ['gold', 'liquid', 'premium', 'high-fidelity', 'metallic'],
        mood: 'Premium',
        colorPalette: ['#f59e0b', '#fbbf24', '#0a0c14']
    },
    'premium-crystal-light': {
        id: 'premium-crystal-light',
        url: '/videos/backgrounds/premium-crystal-light.mp4',
        originalSource: '_premium_cinematic_202601101145_gap4s.mp4',
        description: "Crystalline light refraction and patterns.",
        tags: ['crystal', 'light', 'refraction', 'geometry', 'premium'],
        mood: 'Ethereal',
        colorPalette: ['#818cf8', '#c084fc', '#0a0c14']
    },
    'premium-abstract-energy': {
        id: 'premium-abstract-energy',
        url: '/videos/backgrounds/premium-abstract-energy.mp4',
        originalSource: '_premium_cinematic_202601101146_y1vni.mp4',
        description: "Abstract energy field visualization.",
        tags: ['energy', 'field', 'abstract', 'vibrant', 'light'],
        mood: 'Dynamic',
        colorPalette: ['#f43f5e', '#fb7185', '#0a0c14']
    }
};

export function getVideoAsset(id: string): VideoAsset | undefined {
    return VIDEO_REGISTRY[id];
}

export function getAllVideos(): VideoAsset[] {
    return Object.values(VIDEO_REGISTRY);
}
