
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PAGES_DIR = path.resolve(__dirname, '../../client/src/pages');

function getPageInfo(filename: string) {
    const name = filename.replace('.tsx', '');
    let pathName = '/' + name;
    if (name === 'home') pathName = '/';

    // Read file to get title if possible
    let content = "";
    try {
        content = fs.readFileSync(path.join(PAGES_DIR, filename), 'utf-8');
    } catch (e) { return null; }

    // Try to find title
    let title = name.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '); // Fallback
    const titleMatch = content.match(/seoTitle=["']([^"']+)["']/);
    if (titleMatch) title = titleMatch[1].split('|')[0].trim();
    else {
        const docTitle = content.match(/document\.title\s*=\s*["']([^"']+)["']/);
        if (docTitle) title = docTitle[1].split('|')[0].trim();
    }

    return {
        id: `static-${name}`,
        key: name,
        title: title,
        path: pathName,
        parentKey: null,
        status: 'published',
        pageType: 'page',
        template: 'default',
        clusterKey: null
    };
}


function extractRoutesFromApp(): Map<string, string> {
    const appPath = path.resolve(__dirname, '../../client/src/App.tsx');
    const appContent = fs.readFileSync(appPath, 'utf-8');

    // 1. Map ComponentName -> Filename (basename)
    // const VarName = lazy(() => import("@/pages/filename"));
    const componentToFile = new Map<string, string>();
    const importRegex = /const\s+(\w+)\s*=\s*lazy\(\(\)\s*=>\s*import\("@\/pages\/([^"]+)"\)\);/g;
    for (const match of appContent.matchAll(importRegex)) {
        componentToFile.set(match[1], match[2]); // e.g. "BioelectricWaterPage" -> "bioelectric-water"
    }

    // 2. Map RoutePath -> ComponentName
    // <Route path="/actual/path" component={VarName} />
    const routeToComponent = new Map<string, string>();
    const routeRegex = /<Route\s+path="([^"]+)"\s+component={(\w+)}\s*\/>/g;
    for (const match of appContent.matchAll(routeRegex)) {
        routeToComponent.set(match[1], match[2]); // e.g. "/science/bioelectric-water" -> "BioelectricWaterPage"
    }

    // 3. Build Filename -> RoutePath map
    const fileToRoute = new Map<string, string>();
    for (const [routePath, componentName] of routeToComponent.entries()) {
        const filename = componentToFile.get(componentName);
        if (filename) {
            fileToRoute.set(filename, routePath);
        }
    }

    return fileToRoute;
}

function main() {
    const routeMap = extractRoutesFromApp();
    const files = fs.readdirSync(PAGES_DIR).filter(f => f.endsWith('.tsx'));
    const pages = [];

    const excludes = ['_app.tsx', '_document.tsx', 'sitemap.tsx', 'not-found.tsx', 'coming-soon.tsx', 'admin.tsx', 'scrolling-effects-demo.tsx', 'gold-icons-preview.tsx', 'gold-loader-preview.tsx', 'torus-preview.tsx', 'experiments-index.tsx', 'lab-measurements.tsx', 'motion-lab.tsx'];

    console.log(`Found ${routeMap.size} mapped routes from App.tsx`);

    for (const file of files) {
        if (excludes.includes(file)) continue;

        const page = getPageInfo(file);
        if (page) {
            // Override path if found in App.tsx mapping
            const definedPath = routeMap.get(page.key);
            if (definedPath) {
                page.path = definedPath;
            } else {
                // If not found in App.tsx but exists in pages dir, it's an orphan or not routed
                // We should probably skip it or mark as draft, but strictly following App.tsx is safer for sitemap
                // console.warn(`Warning: Page ${file} has no route in App.tsx. Using default ${page.path}`);
                // Only include if it has a route or is home
                if (page.path !== '/') {
                    continue; // Skip pages that aren't in App.tsx
                }
            }
            pages.push(page);
        }
    }

    // Sort by path
    pages.sort((a, b) => a.path.localeCompare(b.path));

    const outputPath = path.resolve(__dirname, '../../client/src/lib/static-sitemap.ts');
    const fileContent = `// Auto-generated by server/scripts/generate-sitemap-list.ts
export const STATIC_SITEMAP = ${JSON.stringify(pages, null, 2)};
`;
    fs.writeFileSync(outputPath, fileContent);
    console.log(`Generated ${pages.length} pages to ${outputPath}`);
}

main();
