
import { db } from "../db";
import { pages } from "@shared/schema";
import fs from "fs";
import path from "path";
import { eq } from "drizzle-orm";

async function parseGapReport() {
    console.log("Parsing Sitemap Gap Report...");

    const reportPath = path.join(process.cwd(), "sitemap_gap_report.md");
    const content = fs.readFileSync(reportPath, "utf-8");
    const lines = content.split("\n");

    const pagesToCreate: any[] = [];
    let currentCluster = "uncategorized";
    let inCreateSection = false;

    // Helper to map report clusters to DB keys
    const clusterMap: Record<string, string> = {
        "Core & Entry": "home",
        "Shop": "shop",
        "Product": "shop",
        "Water Science": "water_science",
        "Mineral Science": "mineral_science",
        "Crystalline": "crystalline_matrix",
        "Bioelectricity": "bioelectricity",
        "Sulfur": "sulfur_pathways",
        "Microbiome": "minerals_microbiome",
        "Liquid Crystal": "liquid_crystal_biology",
        "Spiritual": "spiritual_electricity",
        "Terrain": "terrain_model",
        "Trust": "trust_lab",
        "Brand": "about",
        "Support": "support",
        "Blog": "blog"
    };

    function getClusterKey(header: string) {
        for (const [key, val] of Object.entries(clusterMap)) {
            if (header.includes(key)) return val;
        }
        return "uncategorized";
    }

    for (const line of lines) {
        // Detect Section 2 Start
        if (line.includes("## 2. Action Items: Create New Pages")) {
            inCreateSection = true;
            continue;
        }
        // Detect Section 3 Start (End of Section 2)
        if (line.includes("## 3. Deprecated")) {
            inCreateSection = false;
        }

        if (inCreateSection) {
            // ### 1. Core & Entry Cluster
            if (line.startsWith("### ")) {
                currentCluster = getClusterKey(line);
            }
            // - [ ] **/start-here**: Start Here – How to Navigate Andara Ionic
            // Regex to extract path and title
            const match = line.match(/- \[ \] \*\*(.*?)\*\*: (.*)/);
            if (match) {
                const rawPath = match[1].trim();
                const title = match[2].trim();

                // Check if page already exists in DB
                const existingPageResult = await db.select().from(pages).where(eq(pages.path, rawPath)).limit(1);
                const exists = existingPageResult[0];

                if (!exists) {
                    pagesToCreate.push({
                        path: rawPath,
                        title: title,
                        cluster: currentCluster,
                        status: 'draft',
                        aiStartupHtml: `<h1>${title}</h1><p>Content to be generated by Visual Interpreter.</p>`
                    });
                } else {
                    console.log(`Skipping existing: ${rawPath}`);
                }
            }
        }
    }

    console.log(`\nFound ${pagesToCreate.length} pages to create from Gap Report.`);

    // Write to JSON for the generator
    const outputPath = path.join(process.cwd(), "server/scripts/missing-pages-list.json");
    fs.writeFileSync(outputPath, JSON.stringify(pagesToCreate, null, 2));
    console.log(`Saved list to ${outputPath}`);

    // Output breakdown
    const byCluster: Record<string, number> = {};
    pagesToCreate.forEach(p => byCluster[p.cluster] = (byCluster[p.cluster] || 0) + 1);
    console.log("\n--- TO CREATE BY CLUSTER ---");
    Object.entries(byCluster).forEach(([c, n]) => console.log(`${c}: ${n}`));

    process.exit(0);
}

parseGapReport().catch(console.error);
